version: '3.9'

services:
  frontend:
    build:
      context: .
      args:
        NX_API_URL: ${NX_API_URL}
        NX_TELEGRAM_DISCUSSION: ${NX_TELEGRAM_DISCUSSION}
    ports:
      - 4200:80
